name: mini
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Ensuring compatibility with Dart SDK 3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7  # Upgraded to latest stable
  file_picker: ^8.0.0  # Upgraded for Flutter 3.7+ support
  intl: ^0.18.1  # Latest version
  hive: ^2.2.3  # Still latest
  hive_flutter: ^1.1.0  # Still latest
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  # Adjusted to compatible version
  build_runner: ^2.4.6  # Latest for compatibility
  hive_generator: ^2.0.0  # Upgraded for Hive compatibility

flutter:
  uses-material-design: true

  assets:
    - assets/images/
